"""Add note table

Revision ID: 8ed5c1291495
Revises: 5b3efea308c9
Create Date: 2026-02-20 17:09:20.828439

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ed5c1291495'
down_revision: Union[str, None] = '5b3efea308c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notes',
        sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column('hash', sa.String(length=36),
            server_default=sa.text('UUID()'),
            unique=True, index=True,
            nullable=False
        ),
        sa.Column('organization_id', sa.BigInteger(),
            server_default=sa.text('0'),
            nullable=False
        ),
        sa.Column('entity_type_id', sa.BigInteger(),
            server_default=sa.text('0'),
            nullable=False
        ),
        sa.Column('reference_id', sa.BigInteger(),
            server_default=sa.text('0'),
            nullable=False
        ),
        sa.Column('title', sa.String(length=255),
            nullable=False
        ),
        sa.Column('content', sa.Text(), nullable=False),
        sa.Column('is_pinned', sa.Boolean(),
            server_default=sa.text('0'),
            nullable=False
        ),
        sa.Column('is_archived', sa.Boolean(),
            server_default=sa.text('0'),
            nullable=False
        ),
        sa.Column('created_at', sa.DateTime(timezone=True),
            server_default=sa.text('UTC_TIMESTAMP()'),
            nullable=False
        ),
        sa.Column('created_by', sa.BigInteger(),
            server_default=sa.text('0'),
            nullable=False
        ),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('updated_by', sa.BigInteger(), nullable=True),
        sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('deleted_by', sa.BigInteger(), nullable=True),
        sa.Column('is_active', sa.Boolean(),
            server_default=sa.text('1'),
            nullable=False
        ),
        sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
        sa.PrimaryKeyConstraint('id'),
        if_not_exists=True
    )
    op.create_index(
        op.f('ix_notes_id'), 'notes', ['id'], unique=False
    )
    op.create_index(
        op.f('ix_notes_organization_id'), 'notes', ['organization_id'], unique=False
    )
    op.create_index(
        op.f('ix_notes_created_by'), 'notes', ['created_by'], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index(op.f('ix_notes_created_by'), table_name='notes')
    op.drop_index(op.f('ix_notes_organization_id'), table_name='notes')
    op.drop_index(op.f('ix_notes_hash'), table_name='notes')
    op.drop_index(op.f('ix_notes_id'), table_name='notes')
    op.drop_table('notes', if_exists=True)
    # ### end Alembic commands ###
