"""Add user table

Revision ID: fddfdfe7300d
Revises: 2c474c219439
Create Date: 2026-02-23 23:02:34.108435

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fddfdfe7300d'
down_revision: Union[str, None] = '2c474c219439'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
        sa.Column('id', sa.BigInteger(),
            autoincrement=True, nullable=False
        ),
        sa.Column('hash', sa.String(length=36),
            server_default=sa.text('UUID()'),
            unique=True, index=True,
            nullable=False
        ),
        sa.Column('organization_id', sa.BigInteger(),
            server_default=sa.text('0'),
            nullable=False, index=True
        ),
        sa.Column('type_id', sa.BigInteger(),
            server_default=sa.text('0'),
            nullable=False, index=False
        ),
        sa.Column('title', sa.String(length=128),
            nullable=True
        ),
        sa.Column('first_name', sa.String(length=64),
            nullable=False
        ),
        sa.Column('middle_name', sa.String(length=64),
            nullable=True
        ),
        sa.Column('last_name', sa.String(length=64),
            nullable=True
        ),
        sa.Column('avatar', sa.String(length=4000),
            nullable=True
        ),
        sa.Column('date_of_birth', sa.DateTime(),
            nullable=True
        ),
        sa.Column('gender_id', sa.BigInteger(),
            server_default=sa.text('0'),
            nullable=False
        ),
        sa.Column('language_id', sa.BigInteger(),
            server_default=sa.text('0'),
            nullable=False
        ),
        sa.Column('virtual_phone_number', sa.String(length=20),
            nullable=True
        ),
        sa.Column('is_pool', sa.Boolean(),
            server_default=sa.text('0'),
            nullable=False
        ),
        sa.Column('created_at', sa.DateTime(timezone=True),
            server_default=sa.text('UTC_TIMESTAMP()'),
            nullable=False
        ),
        sa.Column('created_by', sa.BigInteger(),
            server_default=sa.text('0'),
            nullable=False
        ),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('updated_by', sa.BigInteger(), nullable=True),
        sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('deleted_by', sa.BigInteger(), nullable=True),
        sa.Column('is_active', sa.Boolean(),
            server_default=sa.text('1'),
            nullable=False
        ),
        sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
        sa.PrimaryKeyConstraint('id'),
        if_not_exists=True
    )
    # ### end Alembic commands ###

def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index(op.f('ix_users_organization_id'), table_name='users')
    op.drop_index(op.f('ix_users_hash'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users', if_exists=True)
    # ### end Alembic commands ###
